# Generated by Django 3.0.4 on 2020-03-27 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoModel',
            new_name='TodoItem',
        ),
    ]
